apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: backend-tests-dotnet-basic-hmgxwjsq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: backend-tests-dotnet-basic-hmgxwjsq 
  name: backend-tests-dotnet-basic-hmgxwjsq
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: backend-tests-dotnet-basic-hmgxwjsq 
